// <auto-generated />
using System;
using AlexGolikov.UrlShortener.Data.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AlexGolikov.UrlShortener.Data.DB.Migrations
{
    [DbContext(typeof(UrlShortenerContext))]
    [Migration("20211001123228_RequiredOriginalUrl")]
    partial class RequiredOriginalUrl
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("AlexGolikov.UrlShortener.Domain.Models.Entities.OriginalUrl", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DateTime");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.ToTable("OriginalUrls");
                });

            modelBuilder.Entity("AlexGolikov.UrlShortener.Domain.Models.Entities.ShortUrl", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DateTime");

                    b.Property<Guid>("OriginalUrlId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OriginalUrlId");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.ToTable("ShortUrls");
                });

            modelBuilder.Entity("AlexGolikov.UrlShortener.Domain.Models.Entities.ShortUrl", b =>
                {
                    b.HasOne("AlexGolikov.UrlShortener.Domain.Models.Entities.OriginalUrl", "OriginalUrl")
                        .WithMany()
                        .HasForeignKey("OriginalUrlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OriginalUrl");
                });
#pragma warning restore 612, 618
        }
    }
}
